coverage:
  status:
    project:
      default: false
      ios:
        target: 75%
        flags: ios
      android:
        target: 90%
        android: android
flags:
  ios:
    path:
      - "platforms/apple/Sources/Nimbus"
  android:
    path:
      - "platforms/android/nimbus/src/main"
    ignore:
      - "platforms/apple/Sources/NimbusTests"
      - "platforms/apple/Sources/Nimbus/Templates"
