coverage:
  status:
    project:
      default: false # disable the default status that measures entire project
      android:
        target: auto
        threshold: 1%
        paths:
          - "platforms/android/modules/(.*)/src/main"
      ios:
        target: auto
        threshold: 1%
        paths:
          - "platforms/apple/Sources/(.*)"
    patch: off

ignore:
  - "platforms/apple/Sources/NimbusTests"
  - "platforms/apple/Sources/Nimbus/Templates"
