coverage:
  status:
    project:
      default: false
      nimbus:
        target: auto
        threshold: 1%
        paths:
          - "platforms/apple/Sources/Nimbus"
          - "platforms/android/modules/(.*)/src/main"
    patch: off

ignore:
  - "platforms/apple/Sources/NimbusTests"
  - "platforms/apple/Sources/Nimbus/Templates"
