coverage:
  status:
    project:
      default: false
      nimbus:
        target: 75%
        paths:
          - "platforms/apple/Sources/Nimbus"
          - "platforms/android/nimbus/src/main"
    patch: off

ignore:
  - "platforms/apple/Sources/NimbusTests"
  - "platforms/apple/Sources/Nimbus/Templates"
