version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.0"

    steps:
      - checkout

      - run:
          name: Build iOS
          command: make ios.build

      - run:
          name: Test iOS
          command: make ios.test

      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
