# loosely based on https://github.com/CircleCI-Public/circleci-demo-react-native

version: 2
jobs:
  build-and-test-ios:
    macos:
      xcode: "9.0"

    steps:
      - checkout

      - run:
          name: Build iOS
          command: make ios.build

      - run:
          name: Test iOS
          command: make ios.test

  build-and-test-android:
    docker:
      - image: circleci/android:api-27-node8-alpha

    steps:
      - checkout

      - run:
          name: Build Android
          command: make android.build

      - run:
          name: Test Android
          command: make android.test

workflows:
  version: 2
  build-and-test:
    jobs:
      # - build-and-test-ios
      - build-and-test-android
