# tip: you can test circleci configs locally https://circleci.com/docs/2.0/local-cli/

version: 2
jobs:
  build-and-test-ios:
    macos:
      xcode: "10.1.0"

    shell: /bin/bash --login -eo pipefail

    steps:
      - checkout

      - run:
          name: Prime Simulator
          command: xcrun instruments -w "iPhone 7 (12.1) [" || true

      - run:
          name: Build Nimbus core
          command: |
            npm install
            npm run build

      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.5.3" > ~/.ruby-version

      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf

      - run:
          name: CocoaPods
          working_directory: platforms/apple
          command: |
            gem update bundler
            bundle install
            bundle exec pod install

      - run:
          name: Build iOS
          working_directory: platforms/apple
          command: xcodebuild build -workspace Nimbus.xcworkspace -scheme Nimbus -configuration Debug -sdk iphonesimulator -derivedDataPath build/Debug -destination 'OS=12.1,platform=iOS Simulator,name=iPhone 7'

      - run:
          name: Test iOS
          working_directory: platforms/apple
          command: xcodebuild test -workspace Nimbus.xcworkspace -scheme Nimbus -configuration Debug -sdk iphonesimulator -derivedDataPath build/Debug -destination 'OS=12.1,platform=iOS Simulator,name=iPhone 7'

      - run:
          name: Lint CocoaPod Spec
          working_directory: platforms/apple
          command: bundle exec pod lib lint --private ../../Nimbus.podspec

  build-and-test-android:
    docker:
      - image: circleci/android:api-27-node8-alpha

    steps:
      - checkout

      - run:
          name: Build Android
          working_directory: platforms/android
          command: ./gradlew assembleDebug

      - run:
          name: Test Android
          working_directory: platforms/android
          command: ./gradlew testDebugUnitTest

  build-and-test-ts:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run:
          name: Build and Lint Typescript
          command: |
            npm install
            npm run build
            npm run lint
      
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test-ios
      - build-and-test-android
      - build-and-test-ts
