# tip: you can test circleci configs locally https://circleci.com/docs/2.0/local-cli/

version: 2
jobs:
  build-and-test-macos:
    macos:
      xcode: "11.3.1"

    shell: /bin/bash --login -eo pipefail

    steps:
      - checkout

      - run:
          name: Build nimbus-bridge
          command: |
            npm install

      - restore_cache:
          keys:
            - v1-pods-{{ checksum "platforms/apple/Podfile.lock" }}
            - v1-pods

      - restore_cache:
          keys:
            - v1-bundler-{{ checksum "platforms/apple/Gemfile.lock" }}
            - v1-bundler

      - run:
          name: CocoaPods
          working_directory: platforms/apple
          command: |
            bundle install
            bundle exec pod install

      - save_cache:
          paths:
            - ./platforms/apple/Pods
          key: v1-pods-{{ checksum "platforms/apple/Podfile.lock" }}

      - save_cache:
          paths:
            - ./platforms/apple/.bundle
          key: v1-bundler-{{ checksum "platforms/apple/Gemfile.lock" }}

      - run:
          name: Build macOS
          working_directory: platforms/apple
          command: xcodebuild build -workspace Nimbus.xcworkspace -scheme NimbusDesktop -configuration Debug -sdk macosx

      - run:
          name: Ensure generated code is up-to-date
          working_directory: platforms/apple
          command: |
            xcodebuild build -workspace Nimbus.xcworkspace -scheme 'Generate Code from Templates'
            git diff-index --quiet HEAD Sources

  build-swiftpm:
    macos:
      xcode: "11.3.1"

    shell: /bin/bash --login -eo pipefail

    steps:
      - checkout
      - run:
          name: Build Swift Package
          command: swift build

  build-and-test-ios:
    macos:
      xcode: "11.3.1"

    shell: /bin/bash --login -eo pipefail

    steps:
      - checkout

      - run:
          name: Prime Simulator
          command: xcrun instruments -w "iPhone 7 (12.4) [" || true

      - run:
          name: Build nimbus-bridge
          command: |
            npm install

      - restore_cache:
          keys:
            - v1-pods-{{ checksum "platforms/apple/Podfile.lock" }}
            - v1-pods

      - restore_cache:
          keys:
            - v1-bundler-{{ checksum "platforms/apple/Gemfile.lock" }}
            - v1-bundler

      - run:
          name: CocoaPods
          working_directory: platforms/apple
          command: |
            bundle install
            bundle exec pod install

      - save_cache:
          paths:
            - ./platforms/apple/Pods
          key: v1-pods-{{ checksum "platforms/apple/Podfile.lock" }}

      - save_cache:
          paths:
            - ./platforms/apple/.bundle
          key: v1-bundler-{{ checksum "platforms/apple/Gemfile.lock" }}

      - run:
          name: Build iOS
          working_directory: platforms/apple
          command: xcodebuild build -workspace Nimbus.xcworkspace -scheme Nimbus -configuration Debug -sdk iphonesimulator -derivedDataPath build/Debug -destination 'OS=12.4,platform=iOS Simulator,name=iPhone 7'

      - run:
          name: Test iOS
          working_directory: platforms/apple
          command: xcodebuild test -workspace Nimbus.xcworkspace -scheme Nimbus -configuration Debug -sdk iphonesimulator -derivedDataPath build/Debug -destination 'OS=12.4,platform=iOS Simulator,name=iPhone 7' -enableCodeCoverage YES

      - run:
          name: Lint CocoaPod Spec
          working_directory: platforms/apple
          command: bundle exec pod lib lint --allow-warnings --private ../../NimbusBridge.podspec

      - run:
          name: Get code coverage
          working_directory: platforms/apple
          command: |
            bundle exec slather coverage -x -b build/Debug --scheme Nimbus ./Nimbus.xcodeproj/

      - run:
          name: Build NimbusJS
          command: |
            npm install
            ./create-nimbus-js.sh

      - run:
          name: Build Swift Docs
          working_directory: platforms/apple
          command: |
            bundle exec jazzy

      - persist_to_workspace:
          root: .
          paths:
            - NimbusJS.zip
            - platforms/apple/cobertura.xml
            - platforms/apple/.build/docs

  create-tagged-release:
    docker:
      - image: circleci/node:10

    steps:
      - attach_workspace:
          at: workspace

      - run:
          name: "Install node github release CLI"
          command: |
            sudo npm install -g github-release-cli

      - run:
          name: "Create GitHub Release"
          command: |
            github-release upload -T ${HYPE_GITHUB_TOKEN} -o ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n ${CIRCLE_TAG} -t ${CIRCLE_TAG} ./workspace/NimbusJS.zip

  build-and-test-android:
    docker:
      - image: circleci/android:api-29-node

    steps:
      - checkout

      - run:
          name: Build Android
          working_directory: platforms/android
          command: ./gradlew assembleDebug

      - run:
          name: Test Android
          working_directory: platforms/android
          command: ./gradlew testDebugUnitTest

      - run:
          name: Lint Android
          working_directory: platforms/android
          command: ./gradlew ktlint

      - run:
          name: Build Kotlin Docs
          working_directory: platforms/android
          command: ./gradlew dokka

      - store_artifacts:
          path: platforms/android/nimbus/build/reports
          destination: reports

      - store_test_results:
          path: platforms/android/nimbus/build/test-results

      - run:
          name: Codecov Android
          working_directory: platforms/android
          command: |
            ./gradlew jacocoTestReport

      - persist_to_workspace:
          root: .
          paths:
            - platforms/android/nimbus/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml
            - platforms/android/nimbus/build/dokka

  build-and-test-ts:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run:
          name: Build and Lint Typescript
          command: |
            npm install
            npm run lint -- -- -f junit -o ~/reports/eslint.xml
      - run:
          name: Build Docs
          working_directory: docs
          command: |
            npm install
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - docs/dist
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports

  upload-coverage:
    docker:
      - image: circleci/android:api-29-node

    steps:
      - checkout

      - attach_workspace:
          at: workspace

      - run:
          name: Upload iOS coverage
          command: |
            bash <(curl -s https://codecov.io/bash) -f ./workspace/platforms/apple/cobertura.xml -X coveragepy -X gcov -X xcode

      - run:
          name: Upload Android coverage
          command: |
            bash <(curl -s https://codecov.io/bash) -f ./workspace/platforms/android/nimbus/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml

  upload-android-release:
    docker:
      - image: circleci/android:api-29-node

    steps:
      - checkout

      - run:
          name: Build and upload Android distribution binaries to Bintray
          working_directory: platforms/android
          command: |
            ./gradlew bintrayUpload

workflows:
  version: 2
  create-release-from-tag:
    jobs:
      - build-and-test-ios:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - build-and-test-android:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - create-tagged-release:
          requires:
            - build-and-test-ios
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - upload-android-release:
          requires:
            - build-and-test-android
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/

  build-and-test:
    jobs:
      - build-and-test-ios
      - build-and-test-macos
      - build-swiftpm
      - build-and-test-android
      - build-and-test-ts
      - upload-coverage:
          requires:
            - build-and-test-ios
            - build-and-test-android
