import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://github.com/Kotlin/kotlinx.serialization
     */
    const val kotlinx_serialization_runtime: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-runtime:" +
            Versions.org_jetbrains_kotlinx_kotlinx_serialization

    /**
     * https://kotlinlang.org/
     */
    const val org_jetbrains_kotlin_kotlin_serialization: String =
            "org.jetbrains.kotlin:kotlin-serialization:" +
            Versions.org_jetbrains_kotlin_kotlin_serialization

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_rules: String = "androidx.test:rules:" + Versions.androidx_test_rules

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.kotlin_scripting_compiler_embeddable

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.kotlin_android_extensions

    /**
     * http://www.github.com/kotlintest/kotlintest
     */
    const val kotest_runner_junit5: String = "io.kotest:kotest-runner-junit5-jvm:" +
            Versions.kotest_runner_junit5

    const val gradle_bintray_plugin: String = "com.jfrog.bintray.gradle:gradle-bintray-plugin:" +
            Versions.gradle_bintray_plugin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.kotlin_gradle_plugin

    /**
     * https://kotlinlang.org/
     */
    const val kotlinx_metadata_jvm: String = "org.jetbrains.kotlinx:kotlinx-metadata-jvm:" +
            Versions.kotlinx_metadata_jvm

    const val dokka_gradle_plugin: String = "org.jetbrains.dokka:dokka-gradle-plugin:" +
            Versions.dokka_gradle_plugin

    const val jacoco_android: String = "com.hiya:jacoco-android:" + Versions.jacoco_android

    /**
     * https://developer.android.com/testing
     */
    const val espresso_core: String = "androidx.test.espresso:espresso-core:" +
            Versions.espresso_core

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" + Versions.kotlin_stdlib

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * https://github.com/square/kotlinpoet
     */
    const val kotlinpoet: String = "com.squareup:kotlinpoet:" + Versions.kotlinpoet

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * https://github.com/pinterest/ktlint
     */
    const val ktlint: String = "com.pinterest:ktlint:" + Versions.ktlint

    /**
     * https://github.com/google/guava
     */
    const val guava: String = "com.google.guava:guava:" + Versions.guava

    /**
     * https://developer.android.com/testing
     */
    const val junit: String = "androidx.test.ext:junit:" + Versions.junit

    /**
     * http://mockk.io
     */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    /**
     * http://github.com/google/truth
     */
    const val truth: String = "com.google.truth:truth:" + Versions.truth

    /**
     * https://github.com/eclipsesource/j2v8
     */
    const val j2v8: String = "com.eclipsesource.j2v8:j2v8:" + Versions.j2v8

    const val json: String = "org.json:json:" + Versions.json

    /**
     * https://github.com/salesforce/k2v8
     */
    const val k2v8: String = "com.salesforce.k2v8:k2v8:" + Versions.k2v8
}
